project:
  type: website

website:
  description: "Machine learning tutorials, Python projects, and dataset engineering."
  site-url: https://Muztahid-2020331021.github.io/Machine-Learning-Blog/
  title: "Machine Learning Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Muztahid-2020331021
      - icon: linkedin
        href: https://www.linkedin.com/in/muztahid-hassan-sajid/ 

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css