{
  "hash": "1cdee432d355dbf81f76b5cab444d28c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: EDA on Visa Dataset (Project)\ndescription: A simple EDA project on the Visa dataset using Python and its libraries.\nauthor: Md Muztahid Hassan\ndate: '2026-05-14 21:15:00'\ntoc: true\nexecute:\n  warning: false\n  echo: true\norder: 9\n---\n\n## Loading the libraries and the dataset\n\nAt first, we need to import the necessary libraries.\n\n::: {#23fb4e6e .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n```\n:::\n\n\nNow we will load the dataset. You can download the dataset from <a href=\"Visadataset.csv\">here</a>.\n\n\n::: {#5a4278f1 .cell execution_count=2}\n``` {.python .cell-code}\ndf = pd.read_csv('Visadataset.csv')\ndf.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>case_id</th>\n      <th>continent</th>\n      <th>education_of_employee</th>\n      <th>has_job_experience</th>\n      <th>requires_job_training</th>\n      <th>no_of_employees</th>\n      <th>yr_of_estab</th>\n      <th>region_of_employment</th>\n      <th>prevailing_wage</th>\n      <th>unit_of_wage</th>\n      <th>full_time_position</th>\n      <th>case_status</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>EZYV01</td>\n      <td>Asia</td>\n      <td>High School</td>\n      <td>N</td>\n      <td>N</td>\n      <td>14513</td>\n      <td>2007</td>\n      <td>West</td>\n      <td>592.2029</td>\n      <td>Hour</td>\n      <td>Y</td>\n      <td>Denied</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>EZYV02</td>\n      <td>Asia</td>\n      <td>Master's</td>\n      <td>Y</td>\n      <td>N</td>\n      <td>2412</td>\n      <td>2002</td>\n      <td>Northeast</td>\n      <td>83425.6500</td>\n      <td>Year</td>\n      <td>Y</td>\n      <td>Certified</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>EZYV03</td>\n      <td>Asia</td>\n      <td>Bachelor's</td>\n      <td>N</td>\n      <td>Y</td>\n      <td>44444</td>\n      <td>2008</td>\n      <td>West</td>\n      <td>122996.8600</td>\n      <td>Year</td>\n      <td>Y</td>\n      <td>Denied</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>EZYV04</td>\n      <td>Asia</td>\n      <td>Bachelor's</td>\n      <td>N</td>\n      <td>N</td>\n      <td>98</td>\n      <td>1897</td>\n      <td>West</td>\n      <td>83434.0300</td>\n      <td>Year</td>\n      <td>Y</td>\n      <td>Denied</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>EZYV05</td>\n      <td>Africa</td>\n      <td>Master's</td>\n      <td>Y</td>\n      <td>N</td>\n      <td>1082</td>\n      <td>2005</td>\n      <td>South</td>\n      <td>149907.3900</td>\n      <td>Year</td>\n      <td>Y</td>\n      <td>Certified</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#052ad40b .cell execution_count=3}\n``` {.python .cell-code}\ndf.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n(25480, 12)\n```\n:::\n:::\n\n\n## Summary of the dataset\n\n::: {#02c4fad6 .cell execution_count=4}\n``` {.python .cell-code}\ndf.describe()\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>no_of_employees</th>\n      <th>yr_of_estab</th>\n      <th>prevailing_wage</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>count</th>\n      <td>25480.000000</td>\n      <td>25480.000000</td>\n      <td>25480.000000</td>\n    </tr>\n    <tr>\n      <th>mean</th>\n      <td>5667.043210</td>\n      <td>1979.409929</td>\n      <td>74455.814592</td>\n    </tr>\n    <tr>\n      <th>std</th>\n      <td>22877.928848</td>\n      <td>42.366929</td>\n      <td>52815.942327</td>\n    </tr>\n    <tr>\n      <th>min</th>\n      <td>-26.000000</td>\n      <td>1800.000000</td>\n      <td>2.136700</td>\n    </tr>\n    <tr>\n      <th>25%</th>\n      <td>1022.000000</td>\n      <td>1976.000000</td>\n      <td>34015.480000</td>\n    </tr>\n    <tr>\n      <th>50%</th>\n      <td>2109.000000</td>\n      <td>1997.000000</td>\n      <td>70308.210000</td>\n    </tr>\n    <tr>\n      <th>75%</th>\n      <td>3504.000000</td>\n      <td>2005.000000</td>\n      <td>107735.512500</td>\n    </tr>\n    <tr>\n      <th>max</th>\n      <td>602069.000000</td>\n      <td>2016.000000</td>\n      <td>319210.270000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe `describe()` method only shows the numerical columns. \n\n## Checking Null values and Data types\n\n::: {#b1c1bf11 .cell execution_count=5}\n``` {.python .cell-code}\ndf.info()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.frame.DataFrame'>\nRangeIndex: 25480 entries, 0 to 25479\nData columns (total 12 columns):\n #   Column                 Non-Null Count  Dtype  \n---  ------                 --------------  -----  \n 0   case_id                25480 non-null  object \n 1   continent              25480 non-null  object \n 2   education_of_employee  25480 non-null  object \n 3   has_job_experience     25480 non-null  object \n 4   requires_job_training  25480 non-null  object \n 5   no_of_employees        25480 non-null  int64  \n 6   yr_of_estab            25480 non-null  int64  \n 7   region_of_employment   25480 non-null  object \n 8   prevailing_wage        25480 non-null  float64\n 9   unit_of_wage           25480 non-null  object \n 10  full_time_position     25480 non-null  object \n 11  case_status            25480 non-null  object \ndtypes: float64(1), int64(2), object(9)\nmemory usage: 2.3+ MB\n```\n:::\n:::\n\n\n::: {#7c48b132 .cell execution_count=6}\n``` {.python .cell-code}\ndf.isnull().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\ncase_id                  0\ncontinent                0\neducation_of_employee    0\nhas_job_experience       0\nrequires_job_training    0\nno_of_employees          0\nyr_of_estab              0\nregion_of_employment     0\nprevailing_wage          0\nunit_of_wage             0\nfull_time_position       0\ncase_status              0\ndtype: int64\n```\n:::\n:::\n\n\n## Exploring the data\n\nFor exploring the data, we need to separate the numerical and categorical columns.\n\n::: {#b9039417 .cell execution_count=7}\n``` {.python .cell-code}\n# Create new DataFrames based on data types\nnumerical_features = df.select_dtypes(exclude=['object'])\ncategorical_features = df.select_dtypes(include=['object'])\n\n# Print the results\nprint(f'We have {len(numerical_features.columns)} numerical features : {numerical_features.columns.tolist()}')\nprint(f'\\nWe have {len(categorical_features.columns)} categorical features : {categorical_features.columns.tolist()}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWe have 3 numerical features : ['no_of_employees', 'yr_of_estab', 'prevailing_wage']\n\nWe have 9 categorical features : ['case_id', 'continent', 'education_of_employee', 'has_job_experience', 'requires_job_training', 'region_of_employment', 'unit_of_wage', 'full_time_position', 'case_status']\n```\n:::\n:::\n\n\nIf we want to know the counts of the unique values in a categorical column, we can use the `value_counts()` method.\n\n::: {#afc1cdc3 .cell execution_count=8}\n``` {.python .cell-code}\ndf['continent'].value_counts()\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\ncontinent\nAsia             16861\nEurope            3732\nNorth America     3292\nSouth America      852\nAfrica             551\nOceania            192\nName: count, dtype: int64\n```\n:::\n:::\n\n\nIf we want to see the result as percentage, we can set the `normalize` parameter to `True`. We can do this for all the categorical columns. \n\n::: {#b80fdedb .cell execution_count=9}\n``` {.python .cell-code}\nfrom IPython.display import display\n\nfor col in categorical_features:\n    print(f\"\\n🔹 Feature: {col.upper()}\")\n    \n    # Calculate, round to 2 decimal places, and convert to a DataFrame\n    summary_df = (df[col].value_counts(normalize=True) * 100).round(2).to_frame(name='Percentage (%)')\n    summary_df.index.name = 'Category'\n    \n    # Render the formatted table\n    display(summary_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n🔹 Feature: CASE_ID\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Percentage (%)</th>\n    </tr>\n    <tr>\n      <th>Category</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>EZYV25480</th>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>EZYV01</th>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>EZYV02</th>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>EZYV03</th>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>EZYV04</th>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>EZYV13</th>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>EZYV12</th>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>EZYV11</th>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>EZYV10</th>\n      <td>0.0</td>\n    </tr>\n    <tr>\n      <th>EZYV09</th>\n      <td>0.0</td>\n    </tr>\n  </tbody>\n</table>\n<p>25480 rows × 1 columns</p>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n🔹 Feature: CONTINENT\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Percentage (%)</th>\n    </tr>\n    <tr>\n      <th>Category</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Asia</th>\n      <td>66.17</td>\n    </tr>\n    <tr>\n      <th>Europe</th>\n      <td>14.65</td>\n    </tr>\n    <tr>\n      <th>North America</th>\n      <td>12.92</td>\n    </tr>\n    <tr>\n      <th>South America</th>\n      <td>3.34</td>\n    </tr>\n    <tr>\n      <th>Africa</th>\n      <td>2.16</td>\n    </tr>\n    <tr>\n      <th>Oceania</th>\n      <td>0.75</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n🔹 Feature: EDUCATION_OF_EMPLOYEE\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Percentage (%)</th>\n    </tr>\n    <tr>\n      <th>Category</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Bachelor's</th>\n      <td>40.16</td>\n    </tr>\n    <tr>\n      <th>Master's</th>\n      <td>37.81</td>\n    </tr>\n    <tr>\n      <th>High School</th>\n      <td>13.42</td>\n    </tr>\n    <tr>\n      <th>Doctorate</th>\n      <td>8.60</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n🔹 Feature: HAS_JOB_EXPERIENCE\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Percentage (%)</th>\n    </tr>\n    <tr>\n      <th>Category</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Y</th>\n      <td>58.09</td>\n    </tr>\n    <tr>\n      <th>N</th>\n      <td>41.91</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n🔹 Feature: REQUIRES_JOB_TRAINING\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Percentage (%)</th>\n    </tr>\n    <tr>\n      <th>Category</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>N</th>\n      <td>88.4</td>\n    </tr>\n    <tr>\n      <th>Y</th>\n      <td>11.6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n🔹 Feature: REGION_OF_EMPLOYMENT\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Percentage (%)</th>\n    </tr>\n    <tr>\n      <th>Category</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Northeast</th>\n      <td>28.24</td>\n    </tr>\n    <tr>\n      <th>South</th>\n      <td>27.54</td>\n    </tr>\n    <tr>\n      <th>West</th>\n      <td>25.85</td>\n    </tr>\n    <tr>\n      <th>Midwest</th>\n      <td>16.90</td>\n    </tr>\n    <tr>\n      <th>Island</th>\n      <td>1.47</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n🔹 Feature: UNIT_OF_WAGE\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Percentage (%)</th>\n    </tr>\n    <tr>\n      <th>Category</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Year</th>\n      <td>90.12</td>\n    </tr>\n    <tr>\n      <th>Hour</th>\n      <td>8.47</td>\n    </tr>\n    <tr>\n      <th>Week</th>\n      <td>1.07</td>\n    </tr>\n    <tr>\n      <th>Month</th>\n      <td>0.35</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n🔹 Feature: FULL_TIME_POSITION\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Percentage (%)</th>\n    </tr>\n    <tr>\n      <th>Category</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Y</th>\n      <td>89.38</td>\n    </tr>\n    <tr>\n      <th>N</th>\n      <td>10.62</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n🔹 Feature: CASE_STATUS\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Percentage (%)</th>\n    </tr>\n    <tr>\n      <th>Category</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Certified</th>\n      <td>66.79</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>33.21</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n> We can use ydata-profiling to automate this process. \n\n**Insights**\n - `case_id` have unique vlaues for each column which can be dropped as it it of no importance\n - `continent` column is highly biased towards asia. hence we can combine other categories to form a single category.\n - `unit_of_wage` seems to be an important column as most of them are yearly contracts.\n\n## Univariate Analysis\nWe will do univariate analysis on the numerical columns and categorical features separately.\n### Numerical Features\n\n::: {#50b3683a .cell execution_count=10}\n``` {.python .cell-code}\nimport math\n\nnum_cols = numerical_features.columns\ntotal_plots = len(num_cols)\nnum_rows = math.ceil(total_plots / 2)\nfig, ax= plt.subplots(num_rows, 2, figsize=(15, 5*num_rows))\nfig.suptitle('Univariate Analysis of Numerical Features', fontsize=20, fontweight='bold', alpha=0.8)\n\naxes = ax.flatten() if total_plots > 1 else [ax]\nfor i in range(len(num_cols)):\n    sns.kdeplot(data=df, x=num_cols[i], color='blue', ax=axes[i])\n    axes[i].set_xlabel(num_cols[i])\n\nfor j in range(total_plots, len(axes)):\n    fig.delaxes(axes[j])\n\nfig.tight_layout()\nfig.subplots_adjust(top=0.95)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-11-output-1.png){width=1430 height=946}\n:::\n:::\n\n\n**Feature-by-Feature Insights**\n\n* **`no_of_employees`**: Highly right-skewed; most are very small companies, but a few massive corporate outliers stretch the tail past 600,000.\n* **`yr_of_estab`**: Left-skewed; most companies are relatively modern (established 1990–2010), with a long tail of much older businesses.\n* **`prevailing_wage`**: Bimodal distribution with two distinct peaks representing hourly wages (near $0) and standard yearly salaries ($50k–$100k).\n\n### Categorical Features\n\n::: {#df25ae7f .cell execution_count=11}\n``` {.python .cell-code}\ncategorical_features=categorical_features.drop(columns=['case_id'])\n\ncat_cols = categorical_features.columns\ntotal_plots = len(cat_cols)\nnum_rows = math.ceil(total_plots / 3)\nfig, ax = plt.subplots(num_rows, 3, figsize=(20, 5*num_rows))\nfig.suptitle('Univariate Analysis of Categorical Features', fontsize=20, fontweight='bold', alpha=0.8)\n\naxes = ax.flatten() if total_plots > 1 else [ax]\n\nfor i in range(len(cat_cols)):\n    sns.countplot(data=df, x=cat_cols[i], ax=axes[i])\n    axes[i].set_xlabel(cat_cols[i])\n\nfor j in range(total_plots, len(axes)):\n    fig.delaxes(axes[j])\n\nfig.tight_layout()\nfig.subplots_adjust(top=0.95)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-12-output-1.png){width=1910 height=1416}\n:::\n:::\n\n\n**Feature-by-Feature Insights**\n\n* **`continent`**: Applicants are overwhelmingly from Asia (16,000+), with Europe and North America trailing far behind.\n* **`education_of_employee`**: The majority hold a Bachelor's or Master's degree, split almost evenly at roughly 10,000 each.\n* **`has_job_experience`**: Applicants with job experience (Y) outnumber those without (N) by a moderate margin.\n* **`requires_job_training`**: Almost all positions (22,000+) do not require additional job training (N).\n* **`region_of_employment`**: Jobs are fairly evenly distributed across the West, Northeast, and South, with very few in the Islands.\n* **`unit_of_wage`**: The vast majority of salaries are calculated on a Yearly basis, making this feature highly imbalanced.\n* **`full_time_position`**: Nearly all applications are for full-time positions (Y), with very few part-time roles represented.\n* **`case_status`**: The approval rate is roughly 2-to-1, with about 17,000 cases Certified and 8,500 Denied.\n\n## Multivariate Analysis\n\nAt first, we will separate the discrete and continuous features from numerical features. \n\n::: {#f3894f98 .cell execution_count=12}\n``` {.python .cell-code}\ndiscrete_features = [col for col in numerical_features.columns if numerical_features[col].nunique() <= 25]\ncontinuous_features = [col for col in numerical_features.columns if numerical_features[col].nunique() > 25]\n\ndiscrete_features=numerical_features[discrete_features]\ncontinuous_features=numerical_features[continuous_features]\n\nprint(f'We have {len(discrete_features.columns)} discrete features : {list(discrete_features.columns)}')\nprint(f'\\nWe have {len(continuous_features.columns)} continuous features : {list(continuous_features.columns)}')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWe have 0 discrete features : []\n\nWe have 3 continuous features : ['no_of_employees', 'yr_of_estab', 'prevailing_wage']\n```\n:::\n:::\n\n\n### Checking Multicollinearity\nIf we want to check the correlation between the numerical features, we can use the `corr()` method. \n\n::: {#ab1a412b .cell execution_count=13}\n``` {.python .cell-code}\ndf.corr(numeric_only=True)\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>no_of_employees</th>\n      <th>yr_of_estab</th>\n      <th>prevailing_wage</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>no_of_employees</th>\n      <td>1.000000</td>\n      <td>-0.017770</td>\n      <td>-0.009523</td>\n    </tr>\n    <tr>\n      <th>yr_of_estab</th>\n      <td>-0.017770</td>\n      <td>1.000000</td>\n      <td>0.012342</td>\n    </tr>\n    <tr>\n      <th>prevailing_wage</th>\n      <td>-0.009523</td>\n      <td>0.012342</td>\n      <td>1.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nBut what about the categorical features? We will use the `Chi-Square test` to check the correlation between the categorical features. \nIn statistics, the **Null Hypothesis** assumes that the two columns have no relationship at all. We assume the `alpha`(Significance level) to be 0.05. Here `alpha` is the threshold we set for rejecting the null hypothesis. \n`P-value` is the result of the chi-square test. If the `p-value` is less than `alpha`, we reject the null hypothesis and conclude that there is a significant association between the feature and the target variable. Otherwise, we fail to reject the null hypothesis, suggesting no significant association between the feature and the target variable. In that case, we may consider dropping the feature from our model.\n\n::: {#9d36afcf .cell execution_count=14}\n``` {.python .cell-code}\nfrom scipy.stats import chi2_contingency\n\nchi2_results = []\n\nfor feature in cat_cols:\n    crosstab = pd.crosstab(df['case_status'], df[feature])\n    chi2, p_value, dof, expected = chi2_contingency(crosstab)\n    if p_value < 0.05: # Checking significance level (alpha = 0.05)\n        decision = 'Reject Null (Significant Relationship)'\n    else:\n        decision = 'Fail to Reject (No Relationship)'\n        \n    chi2_results.append({\n        'Feature': feature,\n        'P-Value': p_value, \n        'Hypothesis Result': decision\n    })\n\nresult = pd.DataFrame(chi2_results)\nresult\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Feature</th>\n      <th>P-Value</th>\n      <th>Hypothesis Result</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>continent</td>\n      <td>8.828798e-74</td>\n      <td>Reject Null (Significant Relationship)</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>education_of_employee</td>\n      <td>0.000000e+00</td>\n      <td>Reject Null (Significant Relationship)</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>has_job_experience</td>\n      <td>1.922560e-206</td>\n      <td>Reject Null (Significant Relationship)</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>requires_job_training</td>\n      <td>1.855647e-01</td>\n      <td>Fail to Reject (No Relationship)</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>region_of_employment</td>\n      <td>2.338664e-63</td>\n      <td>Reject Null (Significant Relationship)</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>unit_of_wage</td>\n      <td>5.193385e-240</td>\n      <td>Reject Null (Significant Relationship)</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>full_time_position</td>\n      <td>4.469975e-02</td>\n      <td>Reject Null (Significant Relationship)</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>case_status</td>\n      <td>0.000000e+00</td>\n      <td>Reject Null (Significant Relationship)</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n**Insights**:\nHere we can see that the 'requires_job_training' feature has a p-value of 0.18, which is greater than our alpha threshold of 0.05. So there is no relationship between the 'requires_job_training' feature and the target variable 'case_status'. Hence we can drop this feature from our model.\n\n### Checking Null values\n\n::: {#7fbc21d9 .cell execution_count=15}\n``` {.python .cell-code}\ndf.isnull().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\ncase_id                  0\ncontinent                0\neducation_of_employee    0\nhas_job_experience       0\nrequires_job_training    0\nno_of_employees          0\nyr_of_estab              0\nregion_of_employment     0\nprevailing_wage          0\nunit_of_wage             0\nfull_time_position       0\ncase_status              0\ndtype: int64\n```\n:::\n:::\n\n\n### Working with coninuous features\n\n::: {#b3a607e5 .cell execution_count=16}\n``` {.python .cell-code}\ncont_cols = continuous_features.columns\nnum_rows = len(cont_cols)\nclr1 = ['#1E90FF', '#DC143C']\nfig, ax = plt.subplots(num_rows, 2, figsize=(10, num_rows*4))\nfig.suptitle('Distribution of Numerical Features By Case Status', fontsize=20, fontweight='bold', alpha=0.8)\n\nfor i, col in enumerate(cont_cols):\n    sns.boxplot(data=df, x='case_status', y=col, hue='case_status', palette=clr1, ax=ax[i, 0])\n    ax[i, 0].set_title(f'Box Plot of {col}', fontsize=14)\n\n    sns.histplot(data=df, x=col, hue='case_status', bins=20, multiple='stack', palette=clr1, ax=ax[i, 1], kde=True, legend=True)\n    ax[i,1].set_title(f'Histogram of {col}', fontsize=14)\n\nfig.tight_layout()\nfig.subplots_adjust(top=0.92)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-17-output-1.png){width=948 height=1134}\n:::\n:::\n\n\n### Initial Analysis Report\n\n* **No of Employees has many outliers which can be Handled in Feature Engineering and `no_of_employees` is Right Skewed.**\n* **`yr_of_estab` is left skewed and some outliers below the lower bound of Box plot.**\n* **`prevailing_wage` is right skewed with outliers above upper bound of box plot.**\n* **There are No missing values in the dataset.**\n* **The `case_id` column can be deleted because each row has unique values.**\n* **The `case_status` column is the target to predict.**\n* **In the Categorical column, features can be made Binary numerical in feature Encoding**\n\n## Visualizing the target variable\n\n::: {#1a7b7bd0 .cell execution_count=17}\n``` {.python .cell-code}\npercentage = df['case_status'].value_counts(normalize=True) * 100\nlabels = percentage.index\n\nfig, ax = plt.subplots(figsize=(10, 6))\ncolors = ['#1188ff', '#e63a2a']\nexplode = (0, 0.1)\nax.pie(percentage, labels=labels, autopct='%1.1f%%', startangle=90, colors=colors, explode=explode, shadow=True)\nax.set_title('Distribution of Case Status', fontsize=16, fontweight='bold')\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-18-output-1.png){width=476 height=487}\n:::\n:::\n\n\nFrom the chart it is seen that the Target Variable is Imbalanced\n**What is imbalanced data?**\n\nImbalanced data occurs when the target class has an uneven distribution of observations. In this dataset, there is a moderate imbalance, as the Certified cases (66.8%) have a significantly higher count than the Denied cases (33.2%).\n\nNow we will try to answer some questions based on the dataset.\n## Does applicant Continent has any impact on Visa status ?\n\n::: {#790252d0 .cell execution_count=18}\n``` {.python .cell-code}\n(df.groupby('continent')['case_status'].value_counts(normalize=True).to_frame(name='percentage(%)')*100).round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>percentage(%)</th>\n    </tr>\n    <tr>\n      <th>continent</th>\n      <th>case_status</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Africa</th>\n      <th>Certified</th>\n      <td>72.05</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>27.95</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Asia</th>\n      <th>Certified</th>\n      <td>65.31</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>34.69</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Europe</th>\n      <th>Certified</th>\n      <td>79.23</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>20.77</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">North America</th>\n      <th>Certified</th>\n      <td>61.88</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>38.12</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Oceania</th>\n      <th>Certified</th>\n      <td>63.54</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>36.46</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">South America</th>\n      <th>Certified</th>\n      <td>57.86</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>42.14</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#a90f503a .cell execution_count=19}\n``` {.python .cell-code}\nplt.figure(figsize=(10, 6))\nsns.countplot(data=df, x='continent', hue='case_status', palette='Accent', edgecolor='black')\nplt.title('Continent vs Visa Status', fontsize=16, fontweight='bold')\nplt.xlabel('Continent')\nplt.ylabel('Count')\nplt.legend(title='Visa Status', fancybox=True)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-20-output-1.png){width=833 height=528}\n:::\n:::\n\n\nIf we want to see only the `certified` cases by continent, we can do the following process.\n\n::: {#4a0fe585 .cell execution_count=20}\n``` {.python .cell-code}\npct_df = pd.crosstab(df['continent'], df['case_status'], normalize='index') * 100\ncert_pct = pct_df['Certified']\nfig, ax = plt.subplots(figsize=(14, 7))\n\nbars = ax.bar(cert_pct.index, cert_pct.values, color='lightgreen', edgecolor='black')\nax.bar_label(bars, fmt='%.1f%%', padding=3, fontsize=12, fontweight='bold')\n\nax.set_title(\"Percentage of Certified Cases by Continent\", fontsize=16, fontweight='bold')\nax.set_xlabel('Continent', fontsize=14)\nax.set_ylabel('Percentage (%)', fontsize=14)\nax.tick_params(axis='x', rotation=0, labelsize=12)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-21-output-1.png){width=1334 height=663}\n:::\n:::\n\n\n**Insights:**\n* As per the Chart Asia applicants applied more than other continents.\n* 43% of Certified applications are from Asia.\n* This is followed by Europe with 11% of Certified applications.\n* Highest chance of getting certified if you are from `Europe` and followed by `Africa`\n\n## Does the education of applicant has any impact on Visa status ?\n\n::: {#10e7cd14 .cell execution_count=21}\n``` {.python .cell-code}\n(df.groupby('education_of_employee')['case_status'].value_counts(normalize=True).to_frame(name='percentage(%)')*100).round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>percentage(%)</th>\n    </tr>\n    <tr>\n      <th>education_of_employee</th>\n      <th>case_status</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Bachelor's</th>\n      <th>Certified</th>\n      <td>62.21</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>37.79</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Doctorate</th>\n      <th>Certified</th>\n      <td>87.23</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>12.77</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">High School</th>\n      <th>Denied</th>\n      <td>65.96</td>\n    </tr>\n    <tr>\n      <th>Certified</th>\n      <td>34.04</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Master's</th>\n      <th>Certified</th>\n      <td>78.63</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>21.37</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#d3817353 .cell execution_count=22}\n``` {.python .cell-code}\nplt.figure(figsize=(12, 6))\nsns.countplot(data=df, x='education_of_employee', hue='case_status', palette='Accent', edgecolor='black')\nplt.title('Education of Employee vs Visa Status', fontsize=16, fontweight='bold')\nplt.xlabel('Education of Employee')\nplt.ylabel('Count')\nplt.legend(title='Visa Status', fancybox=True)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-23-output-1.png){width=973 height=528}\n:::\n:::\n\n\nIf we want to see only the `certified` cases by education, we can do the following process.\n\n::: {#79d86566 .cell execution_count=23}\n``` {.python .cell-code}\npct_df = pd.crosstab(df['education_of_employee'], df['case_status'], normalize='index') * 100\ncert_pct = pct_df['Certified']\nfig, ax = plt.subplots(figsize=(14, 7))\n\nbars = ax.bar(cert_pct.index, cert_pct.values, color='lightgreen', edgecolor='black')\nax.bar_label(bars, fmt='%.1f%%', padding=3, fontsize=12, fontweight='bold')\n\nax.set_title(\"Percentage of Certified Cases by Education of Employee\", fontsize=16, fontweight='bold')\nax.set_xlabel('Education of Employee', fontsize=14)\nax.set_ylabel('Percentage(%)', fontsize=14)\nax.tick_params(axis='x', rotation=0, labelsize=12)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-24-output-1.png){width=1334 height=663}\n:::\n:::\n\n\n**Insights**\n- education status has high impact\n- `Doctorate` and `Master's` graduates have higher cange of being accepted then the others.\n\n## Does applicant's previous work experience has any impact on Visa status ?\n\n::: {#37d760f0 .cell execution_count=24}\n``` {.python .cell-code}\n(df.groupby('has_job_experience')['case_status'].value_counts(normalize=True).to_frame(name='percentage(%)')*100).round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=24}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>percentage(%)</th>\n    </tr>\n    <tr>\n      <th>has_job_experience</th>\n      <th>case_status</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">N</th>\n      <th>Certified</th>\n      <td>56.13</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>43.87</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Y</th>\n      <th>Certified</th>\n      <td>74.48</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>25.52</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#e6bf80a8 .cell execution_count=25}\n``` {.python .cell-code}\nplt.figure(figsize=(12, 6))\nsns.countplot(data=df, x='has_job_experience', hue='case_status', palette='Accent', edgecolor='black')\nplt.title('Job Experience vs Visa Status', fontsize=16, fontweight='bold')\nplt.xlabel('Has Job Experience')\nplt.ylabel('Count')\nplt.legend(title='Visa Status', fancybox=True)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-26-output-1.png){width=982 height=528}\n:::\n:::\n\n\nIf we want to see only the `certified` cases by job experience, we can do the following process.\n\n::: {#77f6794b .cell execution_count=26}\n``` {.python .cell-code}\npct_df = pd.crosstab(df['has_job_experience'], df['case_status'], normalize='index') * 100\ncert_pct = pct_df['Certified'].sort_values(ascending=False)\nfig, ax = plt.subplots(figsize=(14, 7))\n\nbars = ax.bar(cert_pct.index, cert_pct.values, color='lightgreen', edgecolor='black')\nax.bar_label(bars, fmt='%.1f%%', padding=3, fontsize=12, fontweight='bold')\n\nax.set_title(\"Percentage of Certified Cases by Job Experience\", fontsize=16, fontweight='bold')\nax.set_xlabel('Has Job Experience', fontsize=14)\nax.set_ylabel('Percentage(%)', fontsize=14)\nax.tick_params(axis='x', rotation=0, labelsize=12)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-27-output-1.png){width=1334 height=663}\n:::\n:::\n\n\n## If the Employee requires job training, does it make any impact on visa status?\n\n::: {#7ab6e00b .cell execution_count=27}\n``` {.python .cell-code}\n(df.groupby('requires_job_training')['case_status'].value_counts(normalize=True).to_frame(name='percentage(%)')*100).round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=27}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>percentage(%)</th>\n    </tr>\n    <tr>\n      <th>requires_job_training</th>\n      <th>case_status</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">N</th>\n      <th>Certified</th>\n      <td>66.65</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>33.35</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Y</th>\n      <th>Certified</th>\n      <td>67.88</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>32.12</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#95ad6153 .cell execution_count=28}\n``` {.python .cell-code}\nplt.figure(figsize=(12, 6))\nsns.countplot(data=df, x='requires_job_training', hue='case_status', palette='Accent', edgecolor='black')\nplt.title('Job Training vs Visa Status', fontsize=16, fontweight='bold')\nplt.xlabel('Requires Job Training')\nplt.ylabel('Count')\nplt.legend(title='Visa Status', fancybox=True)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-29-output-1.png){width=982 height=528}\n:::\n:::\n\n\nIf we want to see only the `certified` cases by the requirement of job training, we can do the following process.\n\n::: {#3158737d .cell execution_count=29}\n``` {.python .cell-code}\npct_df = pd.crosstab(df['requires_job_training'], df['case_status'], normalize='index') * 100\ncert_pct = pct_df['Certified'].sort_values(ascending=False)\nfig, ax = plt.subplots(figsize=(14, 7))\n\nbars = ax.bar(cert_pct.index, cert_pct.values, color='lightgreen', edgecolor='black')\nax.bar_label(bars, fmt='%.1f%%', padding=3, fontsize=12, fontweight='bold')\n\nax.set_title(\"Percentage of Certified Cases by the Requirement of Job Training\", fontsize=16, fontweight='bold')\nax.set_xlabel('Requires Job Training', fontsize=14)\nax.set_ylabel('Percentage(%)', fontsize=14)\nax.tick_params(axis='x', rotation=0, labelsize=12)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-30-output-1.png){width=1334 height=663}\n:::\n:::\n\n\n## Wages and its impact on Visa status\n\n::: {#2a3ae55c .cell execution_count=30}\n``` {.python .cell-code}\n(df.groupby('unit_of_wage')['case_status'].value_counts(normalize=True).to_frame(name='percentage(%)')*100).round(2)\n```\n\n::: {.cell-output .cell-output-display execution_count=30}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th></th>\n      <th>percentage(%)</th>\n    </tr>\n    <tr>\n      <th>unit_of_wage</th>\n      <th>case_status</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Hour</th>\n      <th>Denied</th>\n      <td>65.37</td>\n    </tr>\n    <tr>\n      <th>Certified</th>\n      <td>34.63</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Month</th>\n      <th>Certified</th>\n      <td>61.80</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>38.20</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Week</th>\n      <th>Certified</th>\n      <td>62.13</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>37.87</td>\n    </tr>\n    <tr>\n      <th rowspan=\"2\" valign=\"top\">Year</th>\n      <th>Certified</th>\n      <td>69.89</td>\n    </tr>\n    <tr>\n      <th>Denied</th>\n      <td>30.11</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#448e2000 .cell execution_count=31}\n``` {.python .cell-code}\nplt.figure(figsize=(12, 6))\nsns.countplot(data=df, x='unit_of_wage', hue='case_status', palette='Accent', edgecolor='black')\nplt.title('Percentage of Cases by Unit of Wage', fontsize=16, fontweight='bold')\nplt.xlabel('Unit of Wage')\nplt.ylabel('Count')\nplt.legend(title='Visa Status', fancybox=True)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-32-output-1.png){width=982 height=528}\n:::\n:::\n\n\nIf we want to see only the `certified` cases by unit of wage, we can do the following process.\n\n::: {#531b30b9 .cell execution_count=32}\n``` {.python .cell-code}\npct_df = pd.crosstab(df['unit_of_wage'], df['case_status'], normalize='index') * 100\ncert_pct = pct_df['Certified'].sort_values(ascending=False)\nfig, ax = plt.subplots(figsize=(14, 7))\n\nbars = ax.bar(cert_pct.index, cert_pct.values, color='lightgreen', edgecolor='black')\nax.bar_label(bars, fmt='%.1f%%', padding=3, fontsize=12, fontweight='bold')\n\nax.set_title(\"Percentage of Certified Cases by Unit of Wage\", fontsize=16, fontweight='bold')\nax.set_xlabel('Unit of Wage', fontsize=14)\nax.set_ylabel('Percentage(%)', fontsize=14)\nax.tick_params(axis='x', rotation=0, labelsize=12)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-33-output-1.png){width=1334 height=663}\n:::\n:::\n\n\nIf we want to see how many duplicate values are there in the dataset, we can use the `duplicated()` method.\n\n::: {#a8ae72c7 .cell execution_count=33}\n``` {.python .cell-code}\ndf.duplicated().sum()\n```\n\n::: {.cell-output .cell-output-display execution_count=33}\n```\nnp.int64(0)\n```\n:::\n:::\n\n\nThere is no duplicate value in the dataset.\n\n## For Feature Engineering: \nwe need to focus on the following points\n\n1. Missing value - No\n2. Categorical handler - Yes\n3. Outlier - Yes\n4. Imbalance - Yes\n5. Duplicate - No\n7. Drop any column - Yes\n8. Scaling - Yes\n9. Transformation - Yes\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}